## Language Processing 1: assignment 2

**Deadline: Nov 11, 23:59**

This assignment has four parts:

In the first part, you will be working on morphology, as you learned it in class. The goal is to extract words in present tense and past tense from the corpora you obtained from the first assignment (English, Spanish and a language of your choice). **You can get 20-40 points here.**

In the second part, you will train some language recognizers based on language models and the corpora you obtained in the first assignment. **You can get 25 points here.**

In the third part, you will have to analyze and extend the Minimum Edit Distance algorithm to return an alignment, and not only the minimum number of operations. Then, you will use that implementation to check the differences in the written forms of present and past tense words. **You can get 40 points here.**

The last part will be about sentiment analysis, where you will implement the Naive Bayes model that we saw in  class. **You can get 60 points here.**

You need **70 points** to pass the assignment.

In [2]:
!pip install "numpy<2"

In [4]:
import nltk

from nltk.tokenize import word_tokenize

# Part 1 (Morphology):

---

## Exercise 1.1: (10 points)

Use `nltk.pos_tag` to Part-Of-Speech tag the texts in English. Use it to obtain words in present tense and in past tense.

This may be helpful:

https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html



In [6]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/whitesungun/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [8]:
def read_file(filename):
    with open(filename, 'r', encoding='utf-8') as f:
        return f.read()

def tokenize_nltk(text):
    return word_tokenize(text)

def pos_tag_tokens(tokens):
    return nltk.pos_tag(tokens)

english_text = read_file('en.txt')
english_tokens = tokenize_nltk(english_text)
tagged_tokens = pos_tag_tokens(english_tokens)

present_tense_verbs = [word for word, tag in tagged_tokens if tag in ['VBP', 'VBZ']]
past_tense_verbs = [word for word, tag in tagged_tokens if tag in ['VBD']]

print("Present tense verbs (first 10):", present_tense_verbs[:10])
print("Past tense verbs (first 10):", past_tense_verbs[:10])

Present tense verbs (first 10): ['ponds', 'below—a', 'have', 'have', 'have', 'doubt', 'are', 'see', 'resist', 'do']
Past tense verbs (first 10): ['lay', 'came', 'looked', 'passed', 'wanted', 'was', 'were', 'had', 'was', 'had']


---

## Exercise 1.2: (10 points)

#### Extra: If you train your own model, you get +10 points

Get a pos-tagger for Spanish and use it to obtain words in present tense and in past tense.

In [22]:
!pip install spacy

  Using cached numpy-2.0.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (114 kB)
Using cached numpy-2.0.2-cp312-cp312-macosx_11_0_arm64.whl (13.5 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.0.2 which is incompatible.
streamlit 1.32.0 requires numpy<2,>=1.19.3, but you have numpy 2.0.2 which is incompatible.
numba 0.59.1 requires numpy<1.27,>=1.22, but you have numpy 2.0.2 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.0.2 which is incompatible.


In [24]:
!pip install numpy==1.26.4

  Using cached numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl (13.7 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
blis 1.0.1 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
thinc 8.3.2 requires numpy<2.1.0,>=2.0.0; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.


In [26]:
!python -m spacy download es_core_news_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 8.9 MB/s eta 0:00:0000:0100:01
✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_sm')


In [30]:
import spacy
from spacy.lang.es.examples import sentences 

nlp = spacy.load("es_core_news_sm")
material = ""

material = ' '.join(sentences)

doc = nlp(material)
print(doc.text)

for token in doc:
    if token.pos_ == "VERB":
        tense = token.morph.get('Tense')
        if tense:
            print(token.text, tense)
        else:
            print(token.text, "No tense information")


Apple está buscando comprar una startup del Reino Unido por mil millones de dólares. Los coches autónomos delegan la responsabilidad del seguro en sus fabricantes. San Francisco analiza prohibir los robots de reparto. Londres es una gran ciudad del Reino Unido. El gato come pescado. Veo al hombre con el telescopio. La araña come moscas. El pingüino incuba en su nido sobre el hielo. ¿Dónde estáis? ¿Quién es el presidente francés? ¿Dónde se encuentra la capital de Argentina? ¿Cuándo nació José de San Martín?
buscando No tense information
comprar No tense information
delegan ['Pres']
analiza ['Pres']
prohibir No tense information
come ['Pres']
Veo ['Pres']
come ['Pres']
incuba ['Imp']
estáis ['Pres']
encuentra ['Pres']
nació ['Past']


---

## Exercise 1.3 (optional): (10 points)

Do it for your extra language. Get a pos-tagger and obtain words in present and past tense.

In [32]:
!pip install ufal.udpipe

In [34]:
!pip show ufal.udpipe

Name: ufal.udpipe
Version: 1.3.1.1
Summary: Bindings to UDPipe library
Home-page: https://ufal.mff.cuni.cz/udpipe
Author: Milan Straka
Author-email: straka@ufal.mff.cuni.cz
License: MPL 2.0
Location: /opt/anaconda3/lib/python3.12/site-packages
Requires: 
Required-by: 


In [ ]:
import ufal.udpipe

model = ufal.udpipe.Model.load('ukrainian-ud-2.5-191206.udpipe')

with open('ukr.txt', 'r', encoding='utf-8') as file:
    text = file.read()

processor = ufal.udpipe.Pipeline(model, 'tokenize', 'lemma', 'upos', 'conllu')
processed_text = processor.process(text)

print(processed_text)

from ufal.udpipe import ProcessingError, Sentence

def get_tense_verbs(text):
    sentence = Sentence()
    sentence.from_conllu(text)
    present_verbs = []
    past_verbs = []

    for word in sentence.words:
        if word.upos == "VERB":  
            if word.feats:
                feats = word.feats.split("|")
                for feat in feats:
                    if "Tense=Pres" in feat:  
                        present_verbs.append(word.form)
                    elif "Tense=Past" in feat: 
                        past_verbs.append(word.form)

        return present_verbs, past_verbs

present, past = get_tense_verbs(processed_text)
print("Present Tense Verbs:", present)
print("Past Tense Verbs:", past)

---

# Part 2 (Language Models)

## Exercise 2.1 (15 points):

Train a language recognizer using character bigrams (pairs of adjacent characters) in the text data. You should train one Language Model for each text that you obtained in the first assignment (English, Spanish and the other language of your choice).

You can use the NLTK library to create a conditional frequency distribution  (`nltk.ConditionalFreqDist`) for bigrams in the data. This  counts the frequency of each pair of adjacent characters in the text.

Then, you should convert this frequency distribution into a conditional probability distribution (`nltk.ConditionalProbDist`) using Maximum Likelihood Estimation (`nltk.MLEProbDist`), where each entry represents the probability of a character given its preceding character.

Using this method, you should obtain three Language Models, which can be used to return a probability of a sequence to belong to each language, given a new sequence of letters (for instance, a sentence).

In [1]:
#YOUR CODE HERE
import nltk
from nltk import bigrams, ConditionalFreqDist, ConditionalProbDist, MLEProbDist
nltk.download('punkt')

with open('en.txt', 'r', encoding='utf-8') as f:
    english_text = f.read()
with open('sp.txt', 'r', encoding='utf-8') as f:
    spanish_text = f.read()
with open('ukr.txt', 'r', encoding='utf-8') as f:
    ukrainian_text = f.read()

def get_cfd(text):
    text_bigrams = list(bigrams(text))  
    return ConditionalFreqDist(text_bigrams)

cfd_english = get_cfd(english_text)
cfd_spanish = get_cfd(spanish_text)
cfd_ukrainian = get_cfd(ukrainian_text)

def get_cpd(cfd):
    return ConditionalProbDist(cfd, MLEProbDist)

cpd_english = get_cpd(cfd_english)
cpd_spanish = get_cpd(cfd_spanish)
cpd_ukrainian = get_cpd(cfd_ukrainian)

def calculate_sequence_probability(text, cpd):
    probability = 1.0
    for bigram in bigrams(text.lower()):
        char1, char2 = bigram
        if cpd[char1].prob(char2) > 0:
            probability *= cpd[char1].prob(char2)
        else:
            probability *= 1e-7
    return probability

test_sentence = "Good morning"

english_prob = calculate_sequence_probability(test_sentence, cpd_english)
spanish_prob = calculate_sequence_probability(test_sentence, cpd_spanish)
ukrainian_prob = calculate_sequence_probability(test_sentence, cpd_ukrainian)

print(f"English Probability: {english_prob}")
print(f"Spanish Probability: {spanish_prob}")
print(f"Ukrainian Probability: {ukrainian_prob}")


[nltk_data] Downloading package punkt to
[nltk_data]     /Users/whitesungun/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


English Probability: 1.8352319598025105e-13
Spanish Probability: 1.9955440512212427e-17
Ukrainian Probability: 9.999999999999994e-78


## Exercise 2.2 (10 points)

Provide 3 examples of sentences and their probability to belong to each language. Do you think that these Language Models are good enough to recognize the language of a text?

These language models, based on character bigrams, are effective for recognizing short texts and distinguishing between languages like English, Spanish, and Ukrainian. However, their accuracy decreases with longer or more complex texts, as they lack contextual understanding. For better performance, more advanced models, such as word-based n-grams or deep learning, could be used to capture broader language patterns.

In [4]:
#YOUR CODE HERE
test_sentences = [
    "Hello, how are you?",
    "Buenos días, ¿cómo estás?",
    "Доброго ранку, як справи?"
]

for sentence in test_sentences:
    english_prob = calculate_sequence_probability(sentence, cpd_english)
    spanish_prob = calculate_sequence_probability(sentence, cpd_spanish)
    ukrainian_prob = calculate_sequence_probability(sentence, cpd_ukrainian)
    print(f" Sentence: '{sentence}'")
    print(f" English Probability: {english_prob}")
    print(f" Spanish Probability: {spanish_prob}")
    print(f" Ukrainian Probability: {ukrainian_prob}\n")


 Sentence: 'Hello, how are you?'
 English Probability: 3.705544053835486e-21
 Spanish Probability: 5.230677018956097e-28
 Ukrainian Probability: 1.181764548951039e-116

 Sentence: 'Buenos días, ¿cómo estás?'
 English Probability: 2.0851180042065683e-76
 Spanish Probability: 7.069983864512341e-28
 Ukrainian Probability: 9.930367504835577e-162

 Sentence: 'Доброго ранку, як справи?'
 English Probability: 9.245584597804221e-162
 Spanish Probability: 9.478065682702833e-162
 Ukrainian Probability: 5.960867225275129e-28



# Part 3 (Minimum Edit Distance)

In this exercise, we give you an implementation of Minimum Edit Distance.

In [6]:
import numpy as np
ops=['i','d','s']

def MED (src_str,trg_str):
    src_str = "#"+src_str
    trg_str = "#"+trg_str
    
    ins_cost = 1
    del_cost = 1
    sub_cost = 2
    
    m = len(src_str)
    n = len(trg_str)
    
    distance_matrix = np.zeros((n,m))

    distance_matrix [:,0] = np.arange(0,n,del_cost)
    
    distance_matrix [0,:] = np.arange(0,m,ins_cost)    
    
    for i in range(1,n): 
        for j in range(1,m): 
            insert = distance_matrix[i-1,j] + ins_cost
            delete = distance_matrix[i,j-1] + del_cost
            if src_str[j]==trg_str[i]:
                substi = distance_matrix[i-1,j-1]
            else:
                substi = distance_matrix[i-1,j-1] + sub_cost

            distance_matrix[i,j] = min([insert,delete,substi])
            which_op = np.argmin([insert,delete,substi])
            
            print (distance_matrix[i,j],i,j, "-",insert,delete,substi, ops[which_op])
            
    print (np.flip(distance_matrix.T, axis=0))
    
    return distance_matrix[-1,-1]

MED ("PRNAP","PAP")

0.0 1 1 - 2.0 2.0 0.0 s
1.0 1 2 - 3.0 1.0 3.0 d
2.0 1 3 - 4.0 2.0 4.0 d
3.0 1 4 - 5.0 3.0 5.0 d
4.0 1 5 - 6.0 4.0 4.0 d
1.0 2 1 - 1.0 3.0 3.0 i
2.0 2 2 - 2.0 2.0 2.0 i
3.0 2 3 - 3.0 3.0 3.0 i
2.0 2 4 - 4.0 4.0 2.0 s
3.0 2 5 - 5.0 3.0 5.0 d
2.0 3 1 - 2.0 4.0 2.0 i
3.0 3 2 - 3.0 3.0 3.0 i
4.0 3 3 - 4.0 4.0 4.0 i
3.0 3 4 - 3.0 5.0 5.0 i
2.0 3 5 - 4.0 4.0 2.0 s
[[5. 4. 3. 2.]
 [4. 3. 2. 3.]
 [3. 2. 3. 4.]
 [2. 1. 2. 3.]
 [1. 0. 1. 2.]
 [0. 1. 2. 3.]]


2.0

### Exercise 3.1 (20 pts):

You have to extend the given implementation so that it returns one alignment. Considering one minimum edit distance, there might be more than one alignment. If you return one possible alignment, the exercise will be considered correct.

The alignment should be a sequence of actions that should be applied to the source string. Considering the source string "intention" and the target string "execution", the function could return

`['d','s','s','-','i','s','-','-','-','-']`

where `d` represents deletion, `i` represents insertion, `s` represents substitution and `-` represents no change. This result could be used to represent the two aligned strings as in Figure 3.23 in SLP2.

In [8]:
def MED_alignment(src_str, trg_str):
    src_str = "#"+src_str
    trg_str = "#"+trg_str
    
    ins_cost = 1
    del_cost = 1
    sub_cost = 2
    
    m = len(src_str)
    n = len(trg_str)
    
    distance_matrix = np.zeros((n,m))
    distance_matrix [:,0] = np.arange(0,n,del_cost)
    distance_matrix [0,:] = np.arange(0,m,ins_cost)
    
    bck = np.zeros((n,m),dtype=str)
    ops=['i','d','s']
    
    for i in range(1,n): 
        for j in range(1,m): #each row
            insert = distance_matrix[i-1,j] + ins_cost
            delete = distance_matrix[i,j-1] + del_cost
            if src_str[j]==trg_str[i]:
                substi = distance_matrix[i-1,j-1]
            else:
                substi = distance_matrix[i-1,j-1] + sub_cost

            distance_matrix[i,j] = min([insert,delete,substi])
            which_op = np.argmin([insert,delete,substi])
            bck[i,j] = ops[which_op]
            
            #print (distance_matrix[i,j],i,j, "-",insert,delete,substi, ops[which_op])
        
    #YOUR CODE HERE
    alignment = []
    i, j = n - 1, m - 1

    while i > 0 or j > 0:
        operation = bck[i, j]
        alignment.append(operation)
        
        if operation == 'i':
            i -= 1  
        elif operation == 'd':
            j -= 1  
        else:  
            i -= 1
            j -= 1 

    alignment.reverse()
    
    return distance_matrix[-1, -1], alignment

    #If you uncomment the following command you can see
    #the distance matrix in the same way
    #that appears in Figure 3.27 from the SLP2 book, page 111.
#    print (np.flip(distance_matrix.T, axis=0))
    
    #RETURN THE LAST ELEMENT
    return distance_matrix[-1,-1]

MED_alignment ("intention","execution")

(8.0, ['s', 'i', 's', '', 's', 'd', 'i', 'i', 'i', 'i', 's', 's', 's', 's'])

### Exercise 3.2: (20 points)

Use your MED method to return the path to see the difference between verbs that are in the present tense and in the past tense. Create a corpus of approximately 10 word pairs (present/past) obtained from the first three exercises. Use MED to see the difference between the present and past tense.

The examples could look like: `play-played`, `run-ran`, `como-comí`, ...

What do you observe? Can you find patterns using this method? Are there differences between the languages? What about your language of choice (optional)?

In [11]:
# English Word Pairs
MED_alignment ("play","played")
MED_alignment ("run","ran")
MED_alignment ("walk","walked")
MED_alignment ("eat","ate")
MED_alignment ("jump","jumped")

(2.0, ['s', 's', 's', 's', 'i', 'i'])

In [13]:
# Spanish Word Pairs 

MED_alignment ("comer","comí")
MED_alignment ("hablar","hablé")
MED_alignment ("vivir","viví")
MED_alignment ("correr","corrí")
MED_alignment ("jugar","jugué")

(4.0, ['s', 's', 's', 'd', 'd', 'i', 'i'])

In [15]:
# Ukrainian Word Pairs 

MED_alignment ("пишу", "писав") # write
MED_alignment ("читаю", "читав")# read
MED_alignment ("говорю", "говорив")# speak
MED_alignment ("бачу", "бачив") # see
MED_alignment ("йду", "йшов")# go

(5.0, ['s', 'd', 'd', 'i', 'i', 'i'])

In [ ]:
English Word Pairs
MED: 2.0
Operations: Primarily substitutions and insertions.
Pattern: Minor changes, with fewer substitutions or insertions, indicating some verbs may only differ by small character changes.

Spanish Word Pairs
MED: 4.0
Operations: Mix of substitutions, deletions, and insertions.
Pattern: Generally more edits needed, with suffixes in present and past forms differing in a predictable way, aligning with the regular conjugation patterns in Spanish.

Ukrainian Word Pairs
MED: 5.0
Operations: Mostly substitutions and deletions.
Pattern: Higher MED score suggests larger morphological changes between present and past tenses. The frequent deletions align with more complex conjugation rules.

Summary:
English requires fewer edits, reflecting more irregular changes.
Spanish uses consistent suffix replacements, shown in moderate MED and balanced operations.
Ukrainian has the highest MED, reflecting more extensive verb transformations.

# Part 4 (Sentiment Analysis)

#### Naive Bayes in movie review data
 
 * Pang, B., Lee, L., & Vaithyanathan, S. (2002, July). [Thumbs up?: sentiment classification using machine learning techniques.](http://www.cs.cornell.edu/home/llee/papers/sentiment.pdf) In Proceedings of the ACL-02 conference on Empirical methods in natural language processing-Volume 10 (pp. 79-86). Association for Computational Linguistics.
 
 * You can download the data from [this website](http://www.cs.cornell.edu/people/pabo/movie-review-data/) (There are different versions, let's all download the 1.1 version of the polarity dataset (`polarity dataset v1.1 (2.2Mb) (includes README.1.1):...`))

### Exercise 4

In this exercise you will implement the model that was presented in the lecture about Sentiment Analysis. The Naive Bayes model!



In [17]:
import os
import numpy as np
import random

In [19]:
def filetowordlist(path, sfx):
    words = []
    for item in sorted(os.listdir(path)):
        if sfx in item:
            f=open(path + item, encoding="iso8859-1")
            lines = [line.strip() for line in f]
            f.close()
            wordsinfile = []
            for l in lines:
                sentencewords = l.split()
                wordsinfile = wordsinfile + sentencewords
            words.append(wordsinfile)
    return words

def log(number):
    return np.log(number)

##### Note: YOU MUST ADJUST THE CELL BELOW

In [21]:
#Change the directory below
#Put the directory where you downloaded the corpus

posreviews_all = filetowordlist("mix20_rand700_tokens_0211/tokens/pos/", ".txt")
negreviews_all = filetowordlist("mix20_rand700_tokens_0211/tokens/neg/", ".txt")

In [23]:
#We set 550 out of the positive reviews and 550 out of the negative reviews for creating a model
#We will teach the model how to make predictions using that portion of the data
posreviews_train = posreviews_all[:550]
negreviews_train = negreviews_all[:550]

#And later, we will be able to use the remaining part to see how well our model performs
#This is called the test data
posreviews_test  = posreviews_all[550:]
negreviews_test  = negreviews_all[550:]

In [25]:
#This is the number of positive and negative reviews in each of the portions of the data (train and test)
len(posreviews_train), len(negreviews_train),len(posreviews_test), len(negreviews_test)

(550, 550, 144, 142)

In [27]:
#These are two lists with all words in each group of reviews
#poswords_train contains a list of words, with concatenated positive reviews
poswords_train=[word for sent in posreviews_train for word in sent]
negwords_train=[word for sent in negreviews_train for word in sent]

Look at a couple of examples:

In [30]:
print (poswords_train[1000:1050])

['the', 'novels', '"', "carlito's", 'way', '"', 'and', '"', 'after', 'hours', '"', 'by', 'edwin', 'torres', ')', 'starring', ':', 'al', 'pacino', ',', 'sean', 'penn', ',', 'penelope', 'ann', 'miller', ',', 'john', 'leguiziamo', ',', 'luis', 'guzman', ',', 'john', 'rebhorn', ',', 'viggio', 'mortensen', ',', 'jorge', 'porcel', "what's", 'shocking', 'about', '"', "carlito's", 'way', '"', 'is', 'how']


In [32]:
print (negwords_train[1000:1050])

['is', 'being', 'semi-consoled', 'by', 'brooke', ',', 'one', 'of', 'his', 'graduate', 'students', '.', 'he', 'lives', 'on', 'arlington', 'road', 'where', 'he', 'makes', 'friends', 'with', 'neighbors', 'oliver', '(', 'robbins', ')', 'and', 'cheryl', 'lang', '(', 'cusack', ')', '.', 'then', 'he', 'begins', 'to', 'suspect', 'that', 'oliver', 'is', 'not', 'the', 'architect', 'he', 'claims', 'to', 'be', ',']


In [34]:
#Vocabularies for positive and negative reviews
pos_vocab_train = set(poswords_train)
neg_vocab_train = set(negwords_train)
vocab_train = pos_vocab_train.union(neg_vocab_train)

#Number of types (vocabulary size)
pos_vocab_size_train = len(pos_vocab_train)
neg_vocab_size_train = len(neg_vocab_train)
vocab_size_train = len(vocab_train)

#Number of words (tokens)
noposwords_train=len(poswords_train)
nonegwords_train=len(negwords_train)

#Number of reviews
noposreviews_train=len(posreviews_train)
nonegreviews_train=len(negreviews_train)

In [36]:
pos_vocab_size_train,noposwords_train,noposreviews_train

(27813, 445289, 550)

In [38]:
log(5),np.log10(5)

(1.6094379124341003, 0.6989700043360189)

#### Exercise 4.1 (12 pts):
Calculate prior probabilities, which are the probabilities of $P(C=positive)$ and $P(C=negative)$.

Instead of saving probabilities, remember the practical issue that we mentioned at the end of the class (we save logprobs (f.ex. `np.log`) instead of regular probabilities).

In [41]:
#YOUR CODE HERE
total_reviews_train = noposreviews_train + nonegreviews_train

prior_probabiolity_pos_train = np.log(noposreviews_train / total_reviews_train)
prior_probabiolity_neg_train = np.log(nonegreviews_train / total_reviews_train)

print ("This is the log probability of a review to be positive:")
print (prior_probabiolity_pos_train)
print ("This is the log probability of a review to be negative:")
print (prior_probabiolity_neg_train)

This is the log probability of a review to be positive:
-0.6931471805599453
This is the log probability of a review to be negative:
-0.6931471805599453


##### Tricky part:

Now we need to estimate the probability of a given word, given a specific class.

$$P\left(w_{k} | c_{i}\right)=\frac{\operatorname{count}\left(w_{k}, c_{i}\right)+1}{\sum_{w \in V} \operatorname{count}\left(w, c_{i}\right) + |V|}$$

$$ logP\left(w_{k} | c_{i}\right) = log (P\left(w_{k} | c_{i}\right))$$

We need some word counts, then.

#### Exercise 4.2 (12 pts):
Calculate word counts for the positive reviews and save them in a variable.

Calculate also the word counts for the negative reviews and save them in another variable.

##### Hint: You can use a dictionary (for each document class or polarity) to save the word counts

In [44]:
#YOUR CODE HERE
from collections import Counter

pos_frequencies = Counter(poswords_train)
neg_frequencies = Counter(negwords_train)
    
print ("The word nice appears "+str(pos_frequencies["nice"])+" times in the positive reviews")
print ("The word nice appears "+str(neg_frequencies["nice"])+" times in the negative reviews")

print ()

print ("The word bad appears "+str(pos_frequencies["bad"])+" times in the positive reviews")
print ("The word bad appears "+str(neg_frequencies["bad"])+" times in the negative reviews")


The word nice appears 118 times in the positive reviews
The word nice appears 92 times in the negative reviews

The word bad appears 223 times in the positive reviews
The word bad appears 509 times in the negative reviews


#### Exercise 4.3 (12 pts):
Now estimate the probability of each word to appear in a positive review. Do the same with negative reviews. When you save them, do as you did in the first exercise, and save log probabilities.

##### Hint: You can use a dictionary (for each document class or polarity) to save the word logprobs

In [47]:
#YOUR CODE HERE

vocab_size_train = len(vocab_train)
noposwords_train = len(poswords_train)
nonegwords_train = len(negwords_train)

pos_logprobs = {}
neg_logprobs = {}

for word in vocab_train:
    pos_prob = (pos_frequencies[word] + 1) / (noposwords_train + vocab_size_train)
    pos_logprobs[word] = np.log(pos_prob)
    
    neg_prob = (neg_frequencies[word] + 1) / (nonegwords_train + vocab_size_train)
    neg_logprobs[word] = np.log(neg_prob)


print ("The log probability of the word nice to appear in the positive reviews is: "+str(pos_logprobs["nice"]))
print ("The log probability of the word nice to appear in the negative reviews is: "+str(neg_logprobs["nice"]))

print ()

print ("The log probability of the word bad to appear in the positive reviews is: "+str(pos_logprobs["bad"]))
print ("The log probability of the word bad to appear in the negative reviews is: "+str(neg_logprobs["bad"]))


The log probability of the word nice to appear in the positive reviews is: -8.310737353530826
The log probability of the word nice to appear in the negative reviews is: -8.438475770037291

The log probability of the word bad to appear in the positive reviews is: -7.678214794787315
The log probability of the word bad to appear in the negative reviews is: -6.736664537472175


#### Exercise 4.4 (12 pts):
When making predictions, we need to handle out-of-vocabulary words carefully. Typically, if a word is not present in the training corpus, it's simply ignored. However, this approach can lead to issues when a word is unique to one class of documents (e.g., only appearing in positive examples).
 
To avoid these problems and ensure a clean implementation, we estimate the log probability of unseen words for both positive and negative classes in our training set. Please save these two probabilities in two variables called `pos_oov_word_logprob` and `neg_oov_word_logprob`.


In [50]:
#YOUR CODE HERE

pos_oov_word_logprob = np.log(1 / (noposwords_train + vocab_size_train))
neg_oov_word_logprob = np.log(1 / (nonegwords_train + vocab_size_train))

print ("The log probability of an out of vocabulary word in the positive reviews is:")
print (pos_oov_word_logprob)
print ("The log probability of an out of vocabulary word in the negative reviews is:")
print (neg_oov_word_logprob)

The log probability of an out of vocabulary word in the positive reviews is:
-13.089860846642354
The log probability of an out of vocabulary word in the negative reviews is:
-12.971075263190547


#### Exercise 4.5 (12 pts):

Now we just need to write a function that will return True if an input review is positive, and False if the input review is negative.

$$\operatorname{argmax}\left(\log P\left(c_{i}\right)+\sum_{k=1}^{N} \log P\left(w_{k} | c_{i}\right)\right)$$

How would you do that?

##### Hint: Keep it simple

In [53]:
def positive_or_not(s):
    log_prob_pos = prior_probabiolity_pos_train
    log_prob_neg = prior_probabiolity_neg_train

    for word in s:
        log_prob_pos += pos_logprobs.get(word, pos_oov_word_logprob)
        log_prob_neg += neg_logprobs.get(word, neg_oov_word_logprob)

    return log_prob_pos > log_prob_neg


In [55]:
review_test = "the movie is nice".split()
positive_or_not(review_test) #This is supposed to be positive

True

In [57]:
review_test = "the movie is bad".split()
positive_or_not(review_test) #This is supposed to be negative

False

In [59]:
review_test = "such an awful movie".split()
positive_or_not(review_test) #This is supposed to be negative

False

In [61]:
review_test = "lovely experience".split()
positive_or_not(review_test) #This is supposed to be positive

True